version: "3.9"
services:
  api:
    build:
      context: ./backend/BailiffOS.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
