name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.sln', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore BailiffOS.sln

      - name: Build
        run: dotnet build BailiffOS.sln --configuration Release --no-restore

      - name: Test with coverage and threshold (TRX logger)
        run: >
          dotnet test BailiffOS.sln --configuration Release --no-build --verbosity normal
          --logger "trx;LogFileName=test-results.trx"
          /p:CollectCoverage=true
          /p:CoverletOutputFormat=cobertura
          /p:CoverletOutput=./TestResults/Coverage/coverage
          /p:Threshold=90
          /p:ThresholdType=line

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-cobertura
          path: |
            **/TestResults/Coverage/coverage.cobertura.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            **/TestResults/Coverage/coverage.cobertura.xml
          flags: unittests
          fail_ci_if_error: false

      - name: Publish Test Results (TRX)
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/TestResults/*.trx
