name: Flutter Analyze & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/bailiffos_mobile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (for Android toolchain)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build web
        run: flutter build web --release

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: frontend/bailiffos_mobile/build/web

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: frontend/bailiffos_mobile/build/app/outputs/flutter-apk/*.apk
